import { r2Url } from "@/lib/image-urls";

export const img = {
  heroPheras: r2Url("hero/pheras"),
  heroVarmala: r2Url("hero/varmala"),
  heroPrewedding: r2Url("hero/prewedding"),
  heroSangeet: r2Url("hero/sangeet"),
  heroMehndi: r2Url("hero/mehndi"),
  heroServices: r2Url("hero/services"),
  heroAbout: r2Url("hero/about"),
  founder: r2Url("founder"),
  pw1: r2Url("pw/1"),
  pw2: r2Url("pw/2"),
  pw3: r2Url("pw/3"),
  pw4: r2Url("pw/4"),
  pw5: r2Url("pw/5"),
  pw6: r2Url("pw/6"),
  pw7: r2Url("pw/7"),
  pw8: r2Url("pw/8"),
  pw9: r2Url("pw/9"),
  pw10: r2Url("pw/10"),
  pw11: r2Url("pw/11"),
  pw12: r2Url("pw/12"),
  pw13: r2Url("pw/13"),
  pw14: r2Url("pw/14"),
  pw15: r2Url("pw/15"),
  pw16: r2Url("pw/16"),
  pw17: r2Url("pw/17"),
  pw18: r2Url("pw/18"),
  pw19: r2Url("pw/19"),
  pw20: r2Url("pw/20"),
  sg2: r2Url("sg/2"),
  sg3: r2Url("sg/3"),
  sg4: r2Url("sg/4"),
  sg5: r2Url("sg/5"),
  mh1: r2Url("mh/1"),
  mh2: r2Url("mh/2"),
  mh3: r2Url("mh/3"),
  mh4: r2Url("mh/4"),
  mh5: r2Url("mh/5"),
  mh6: r2Url("mh/6"),
  mh7: r2Url("mh/7"),
  mh8: r2Url("mh/8"),
  mh9: r2Url("mh/9"),
  mh10: r2Url("mh/10"),
  mh11: r2Url("mh/11"),
  mh12: r2Url("mh/12"),
  mh13: r2Url("mh/13"),
  mh14: r2Url("mh/14"),
  mh15: r2Url("mh/15"),
  mh16: r2Url("mh/16"),
  mh17: r2Url("mh/17"),
  wd1: r2Url("wd/1"),
  wd2: r2Url("wd/2"),
  wd3: r2Url("wd/3"),
  wd4: r2Url("wd/4"),
  wd5: r2Url("wd/5"),
  wd6: r2Url("wd/6"),
  wd7: r2Url("wd/7"),
  wd8: r2Url("wd/8"),
  wd9: r2Url("wd/9"),
  wd10: r2Url("wd/10"),
  wd11: r2Url("wd/11"),
  wd12: r2Url("wd/12"),
  wd13: r2Url("wd/13"),
  wd14: r2Url("wd/14"),
  wd15: r2Url("wd/15"),
  rg1: r2Url("rg/1"),
  rg2: r2Url("rg/2"),
  rg3: r2Url("rg/3"),
  rg4: r2Url("rg/4"),
  rg5: r2Url("rg/5"),
  rg6: r2Url("rg/6"),
  rg7: r2Url("rg/7"),
  rg8: r2Url("rg/8"),
  rg9: r2Url("rg/9"),
  rg10: r2Url("rg/10"),
};

export const logo = r2Url("logo");

export const video = {
  heroSection: r2Url("videos/hero-section"),
  preWedding: r2Url("videos/pre-wedding"),
  sangeet: r2Url("videos/sangeet"),
  mehndi: r2Url("videos/mehndi"),
  wedding: r2Url("videos/wedding"),
} as const;

export const brand = {
  name: "Clickographers Wedding Films",
  short: "Clickographers",
  phones: ["9716284428", "8076561746"],
  whatsapp: "919716284428",
  email: "clickographersart@gmail.com",
  address: "C-32A Third Floor, Spectrum Metro Mall, Noida 201301",
};

export const nav = [
  { label: "Home", to: "/" },
  { label: "About", to: "/about" },
  { label: "Services", to: "/services" },
  { label: "Gallery", to: "/gallery" },
  { label: "Contact", to: "/contact" },
] as const;

export const serviceLinks = [
  { label: "Haldi and Mehendi Photoshoots", to: "/mehndi-photoshoots" },
  { label: "Sangeet Photoshoots", to: "/sangeet" },
  { label: "Wedding Photoshoots", to: "/wedding-photography" },
  { label: "Pre Wedding Photoshoots", to: "/pre-wedding" },
] as const;

export const montage = [
  img.heroPheras,
  img.wd2,
  img.pw2,
  img.sg2,
  img.mh2,
  img.heroVarmala,
  img.pw3,
  img.sg3,
  img.mh3,
  img.wd4,
  img.heroPrewedding,
  img.sg4,
  img.mh4,
  img.wd5,
  img.pw4,
  img.heroSangeet,
  img.mh5,
  img.wd3,
  img.pw5,
  img.heroMehndi,
  img.sg5,
  img.heroServices,
];

export type GalleryItem = {
  src: string;
  alt: string;
  category: "Pre Wedding" | "Sangeet" | "Mehndi" | "Wedding Photography" | "Ring Ceremony";
  tall?: boolean;
};

export const gallery: GalleryItem[] = [
  { src: img.heroPrewedding, alt: "Indian couple walking through a palace courtyard at golden hour", category: "Pre Wedding" },
  { src: img.pw1, alt: "Pre-wedding - couple sharing a beautiful moment together", category: "Pre Wedding" },
  { src: img.pw2, alt: "Couple embracing in a mustard field at sunset", category: "Pre Wedding", tall: true },
  { src: img.pw3, alt: "Couple laughing on stone steps beside a lake", category: "Pre Wedding" },
  { src: img.pw4, alt: "Close portrait of a couple with foreheads touching", category: "Pre Wedding", tall: true },
  { src: img.pw5, alt: "Couple on a Jaipur rooftop terrace", category: "Pre Wedding" },
  { src: img.pw6, alt: "Couple walking hand in hand through a sunlit corridor", category: "Pre Wedding" },
  { src: img.pw7, alt: "Couple sharing a quiet moment by a historic fountain", category: "Pre Wedding", tall: true },
  { src: img.pw8, alt: "Playful couple laughing amidst cascading flower petals", category: "Pre Wedding" },
  { src: img.pw9, alt: "Romantic silhouette of a couple at golden hour", category: "Pre Wedding", tall: true },
  { src: img.pw10, alt: "Couple sitting together on palace steps at dusk", category: "Pre Wedding" },
  { src: img.pw11, alt: "Pre-wedding - couple walking through a heritage monument", category: "Pre Wedding", tall: true },
  { src: img.pw12, alt: "Pre-wedding - couple sharing a candid laugh outdoors", category: "Pre Wedding" },
  { src: img.pw13, alt: "Pre-wedding - couple against a dramatic sunset sky", category: "Pre Wedding", tall: true },
  { src: img.pw14, alt: "Pre-wedding - couple sitting together on heritage steps", category: "Pre Wedding" },
  { src: img.pw15, alt: "Pre-wedding - bride and groom in casual moments", category: "Pre Wedding", tall: true },
  { src: img.pw16, alt: "Pre-wedding - couple walking through lush gardens", category: "Pre Wedding" },
  { src: img.pw17, alt: "Pre-wedding - couple embracing under open sky", category: "Pre Wedding", tall: true },
  { src: img.pw18, alt: "Pre-wedding - couple at a scenic lakeside location", category: "Pre Wedding" },
  { src: img.pw19, alt: "Pre-wedding - bride and groom laughing naturally", category: "Pre Wedding", tall: true },
  { src: img.pw20, alt: "Pre-wedding - couple at a historic fort backdrop", category: "Pre Wedding" },
  { src: img.heroSangeet, alt: "Bride and groom dancing on the sangeet stage", category: "Sangeet" },
  { src: img.sg2, alt: "Dancer twirling in a shimmering lehenga on stage", category: "Sangeet", tall: true },
  { src: img.sg3, alt: "Family dancing together under marigold garlands", category: "Sangeet" },
  { src: img.sg4, alt: "Sangeet stage decor with marigold strings and lanterns", category: "Sangeet" },
  { src: img.sg5, alt: "Groom laughing during a family performance", category: "Sangeet", tall: true },
  { src: img.heroMehndi, alt: "Bride having mehndi applied to her hands", category: "Mehndi" },
  { src: img.mh2, alt: "Finished bridal mehndi detail with gold bangles", category: "Mehndi", tall: true },
  { src: img.mh3, alt: "Bride laughing with friends at her mehndi", category: "Mehndi" },
  { src: img.mh4, alt: "Bridal portrait in green and gold with floral jewellery", category: "Mehndi", tall: true },
  { src: img.mh5, alt: "Bridal jewellery and marigold petals flat lay", category: "Mehndi" },
  { src: img.mh1, alt: "Haldi ceremony - family applying turmeric to the groom", category: "Mehndi" },
  { src: img.mh6, alt: "Haldi ceremony - couple playing with turmeric paste", category: "Mehndi", tall: true },
  { src: img.mh7, alt: "Family celebrating during the haldi ceremony", category: "Mehndi" },
  { src: img.mh8, alt: "Haldi ceremony - bride with turmeric paste on her face", category: "Mehndi" },
  { src: img.mh9, alt: "Mehndi - intricate henna patterns on bride's hands", category: "Mehndi", tall: true },
  { src: img.mh10, alt: "Haldi - family members applying turmeric to the couple", category: "Mehndi" },
  { src: img.mh11, alt: "Mehndi - bride smiling with decorated hands", category: "Mehndi", tall: true },
  { src: img.mh12, alt: "Haldi - playful moments with friends and family", category: "Mehndi" },
  { src: img.mh13, alt: "Mehndi - close-up of detailed henna designs", category: "Mehndi", tall: true },
  { src: img.mh14, alt: "Haldi - couple laughing during the ceremony", category: "Mehndi" },
  { src: img.mh15, alt: "Haldi - family gathering around the couple", category: "Mehndi", tall: true },
  { src: img.mh16, alt: "Mehndi - bride getting mehndi applied by artist", category: "Mehndi" },
  { src: img.mh17, alt: "Haldi - couple dressed in yellow for the ceremony", category: "Mehndi", tall: true },
  { src: img.heroVarmala, alt: "Bride and groom exchanging varmala garlands", category: "Wedding Photography" },
  { src: img.wd2, alt: "Bridal portrait in red and gold lehenga", category: "Wedding Photography", tall: true },
  { src: img.wd3, alt: "Groom portrait in ivory sherwani", category: "Wedding Photography", tall: true },
  { src: img.wd4, alt: "Emotional vidaai moment between bride and her mother", category: "Wedding Photography" },
  { src: img.wd5, alt: "Couple walking through a shower of rose petals", category: "Wedding Photography" },
  { src: img.wd1, alt: "Wedding ceremony - couple during the pheras", category: "Wedding Photography", tall: true },
  { src: img.wd6, alt: "Wedding mandap decorated with flowers and lights", category: "Wedding Photography" },
  { src: img.wd7, alt: "Bride entering the ceremony hall", category: "Wedding Photography" },
  { src: img.wd8, alt: "Groom waiting at the mandap", category: "Wedding Photography", tall: true },
  { src: img.wd9, alt: "Couple exchanging rings at the ceremony", category: "Wedding Photography" },
  { src: img.wd10, alt: "First look moment between bride and groom", category: "Wedding Photography", tall: true },
  { src: img.wd11, alt: "Family portrait during the wedding reception", category: "Wedding Photography" },
  { src: img.wd12, alt: "Bride and groom cutting the wedding cake", category: "Wedding Photography", tall: true },
  { src: img.wd13, alt: "Couple's first dance at the reception", category: "Wedding Photography" },
  { src: img.wd14, alt: "Wedding decor - floral mandap and aisle", category: "Wedding Photography", tall: true },
  { src: img.wd15, alt: "Couple leaving the venue with sparklers", category: "Wedding Photography" },
  { src: img.rg1, alt: "Ring ceremony - couple exchanging rings", category: "Ring Ceremony", tall: true },
  { src: img.rg2, alt: "Ring ceremony - bride and groom smiling at guests", category: "Ring Ceremony" },
  { src: img.rg3, alt: "Ring ceremony - decorated stage with the couple", category: "Ring Ceremony", tall: true },
  { src: img.rg4, alt: "Ring ceremony - close-up of ring exchange moment", category: "Ring Ceremony" },
  { src: img.rg5, alt: "Ring ceremony - couple posing with family on stage", category: "Ring Ceremony", tall: true },
  { src: img.rg6, alt: "Ring ceremony - groom placing ring on bride's finger", category: "Ring Ceremony" },
  { src: img.rg7, alt: "Ring ceremony - bride and groom portrait with floral decor", category: "Ring Ceremony", tall: true },
  { src: img.rg8, alt: "Ring ceremony - celebration moment with family cheering", category: "Ring Ceremony" },
  { src: img.rg9, alt: "Ring ceremony - couple walking together after the ceremony", category: "Ring Ceremony", tall: true },
  { src: img.rg10, alt: "Ring ceremony - decorative ring tray and floral setup", category: "Ring Ceremony" },
];

/** Preview photograph + label shown in the page-transition frame. */
const pageImages: Record<string, { src: string; label: string }> = {
  "/": { src: img.heroPheras, label: "Home" },
  "/about": { src: img.heroAbout, label: "About" },
  "/services": { src: img.heroServices, label: "Services" },
  "/gallery": { src: img.wd5, label: "Gallery" },
  "/contact": { src: img.heroVarmala, label: "Contact" },
  "/pre-wedding": { src: img.heroPrewedding, label: "Pre Wedding" },
  "/sangeet": { src: img.heroSangeet, label: "Sangeet" },
  "/mehndi-photoshoots": { src: img.heroMehndi, label: "Mehndi" },
  "/wedding-photography": { src: img.heroVarmala, label: "Wedding Photography" },
};

export function pageImage(pathname: string) {
  const key = pathname.length > 1 ? pathname.replace(/\/$/, "") : "/";
  return pageImages[key] ?? pageImages["/"]!;
}