/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MehndiPhotoshootsRouteImport } from './routes/mehndi-photoshoots'
import { Route as PreWeddingRouteImport } from './routes/pre-wedding'
import { Route as SangeetRouteImport } from './routes/sangeet'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WeddingPhotographyRouteImport } from './routes/wedding-photography'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MehndiPhotoshootsRoute = MehndiPhotoshootsRouteImport.update({
  id: '/mehndi-photoshoots',
  path: '/mehndi-photoshoots',
  getParentRoute: () => rootRouteImport,
} as any)
const PreWeddingRoute = PreWeddingRouteImport.update({
  id: '/pre-wedding',
  path: '/pre-wedding',
  getParentRoute: () => rootRouteImport,
} as any)
const SangeetRoute = SangeetRouteImport.update({
  id: '/sangeet',
  path: '/sangeet',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingPhotographyRoute = WeddingPhotographyRouteImport.update({
  id: '/wedding-photography',
  path: '/wedding-photography',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/mehndi-photoshoots': typeof MehndiPhotoshootsRoute
  '/pre-wedding': typeof PreWeddingRoute
  '/sangeet': typeof SangeetRoute
  '/services': typeof ServicesRoute
  '/wedding-photography': typeof WeddingPhotographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/mehndi-photoshoots': typeof MehndiPhotoshootsRoute
  '/pre-wedding': typeof PreWeddingRoute
  '/sangeet': typeof SangeetRoute
  '/services': typeof ServicesRoute
  '/wedding-photography': typeof WeddingPhotographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/mehndi-photoshoots': typeof MehndiPhotoshootsRoute
  '/pre-wedding': typeof PreWeddingRoute
  '/sangeet': typeof SangeetRoute
  '/services': typeof ServicesRoute
  '/wedding-photography': typeof WeddingPhotographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/mehndi-photoshoots'
    | '/pre-wedding'
    | '/sangeet'
    | '/services'
    | '/wedding-photography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/mehndi-photoshoots'
    | '/pre-wedding'
    | '/sangeet'
    | '/services'
    | '/wedding-photography'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/mehndi-photoshoots'
    | '/pre-wedding'
    | '/sangeet'
    | '/services'
    | '/wedding-photography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  MehndiPhotoshootsRoute: typeof MehndiPhotoshootsRoute
  PreWeddingRoute: typeof PreWeddingRoute
  SangeetRoute: typeof SangeetRoute
  ServicesRoute: typeof ServicesRoute
  WeddingPhotographyRoute: typeof WeddingPhotographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mehndi-photoshoots': {
      id: '/mehndi-photoshoots'
      path: '/mehndi-photoshoots'
      fullPath: '/mehndi-photoshoots'
      preLoaderRoute: typeof MehndiPhotoshootsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-wedding': {
      id: '/pre-wedding'
      path: '/pre-wedding'
      fullPath: '/pre-wedding'
      preLoaderRoute: typeof PreWeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sangeet': {
      id: '/sangeet'
      path: '/sangeet'
      fullPath: '/sangeet'
      preLoaderRoute: typeof SangeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-photography': {
      id: '/wedding-photography'
      path: '/wedding-photography'
      fullPath: '/wedding-photography'
      preLoaderRoute: typeof WeddingPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  MehndiPhotoshootsRoute: MehndiPhotoshootsRoute,
  PreWeddingRoute: PreWeddingRoute,
  SangeetRoute: SangeetRoute,
  ServicesRoute: ServicesRoute,
  WeddingPhotographyRoute: WeddingPhotographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
